########## دریافت فهرست استان ها #########################################################################
GET   {{address}}/Country/get_province_list HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

########## دریافت اطلاعات استان  #################################################################################
GET   {{address}}/Country/get_province_list/10 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

########## دریافت فهرست شهرها ##########################################################################
GET   {{address}}/Country/get_city_list HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

########## دریافت اطلاعات یک شهر  #################################################################################
GET   {{address}}/Country/get_city_list/450 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}
########## دریافت فهرست شهرهای یک استان ################################################################
GET   {{address}}/ /get_city_by_province_id/8 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}