#### دریافت فهرست قبض های کاربر ############################################################
GET   {{address}}/Profile/Bills?page=1&inputBillTitle=&inputBillNumberId=&inputPersonLastName&inputPersonLastName=&inputPersonNationalCode=&inputPersonPhone= HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json 

########## دریافت تمامی قبض های کاربر ######################################################
GET   {{address}}/Profile/Bills/get_all HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

########## دریافت جزئیات یک قبض کاربر ######################################################
GET   {{address}}/Profile/Bills/get_by_id/1207134412221 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
########## دریافت جزئیات یک قبض کاربر ######################################################
GET   {{address}}/Profile/Bills/get_by_guid/b9a6f23a-524a-452e-af50-85cc6b940270 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

########## افزودن قبض #######################################################################
POST   {{address}}/Profile/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillTitle": "قبض کارخانه",
    "inputBillNumberId": "8815739301320"
}
########## ویرایش قبض #######################################################################
PUT   {{address}}/Profile/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputBillTitle": "قبض کارخانه زنجان",
    "inputBillNumberId": "1207134412221"
}
########## حذف قبض ##########################################################################
POST   {{address}}/Profile/Bills/delete_bill HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270"
}
########## فعال سازی/عدم حذف قبض ###########################################################
POST   {{address}}/Profile/Bills/active_bill HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270"
}
########## درج اطلاعات حقوقی و حقیقی قبض ###################################################
POST   {{address}}/Profile/Bills/add_legal_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputRealName": "پدرام",
    "inputRealLastName": "محمدی",
    "inputRealNationalCode": "2541224518",
    "inputRealPhone": "09125745214",
    "inputRealProvinceId": "8",
    "inputRealCityId": "450",
    "inputRealAddress": "تهران شهریار خیابان ولیعصر عج الله تعالی فرجه الشریف",
    "inputLegalOrganizationName": "سازمان آب و فاضله ی آب",
    "inputLegalFinanceCode": "5541245",
    "inputLegalCompanyId": "12355001",
    "inputLegalRegisterNumber": "2258",
    "inputLegalPhone": "02155442211",
    "inputLegalProvinceId": "1",
    "inputLegalCityId": "459", 
    "inputLegalAddress": "تهران شهریار خیابان "
}
########## ویرایش اطلاعات حقوقی و حقیقی قبض ###############################################
PUT   {{address}}/Profile/Bills/edit_legal_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputRealName": "مهسا",
    "inputRealLastName": "محمدی",
    "inputRealNationalCode": "2541224518",
    "inputRealPhone": "09125745214",
    "inputRealProvinceId": "8",
    "inputRealCityId": "450",
    "inputRealAddress": "تهران شهریار خیابان ولیعصر عج الله تعالی فرجه الشریف",
    "inputLegalOrganizationName": "سازمان آب و فاضله ی آب",
    "inputLegalFinanceCode": "5541245",
    "inputLegalCompanyId": "12355001",
    "inputLegalRegisterNumber": "2258",
    "inputLegalPhone": "02155442211",
    "inputLegalProvinceId": "1",
    "inputLegalCityId": "459", 
    "inputLegalAddress": "تهران شهریار خیابان "
}

########## ثبت نوع اطلاعات موجود در پیش فاکتور ###############################################
POST   {{address}}/Profile/Bills/set_factor_type HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputBillFactorPrintType": "Legal"
}


##########  دریافت اطلاعات مصرف کلی قبض کاربر ###########################################
GET {{address}}/Profile/Bills/power_data/b9a6f23a-524a-452e-af50-85cc6b940270 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json 
##########  دریافت سابقه مصرف قبض کاربر ################################################
GET {{address}}/Profile/Bills/sale_data/b9a6f23a-524a-452e-af50-85cc6b940270 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
##########  دریافت میانگین مصرف قبض################################################
GET {{address}}/Profile/Bills/avg_cons/8815739301320 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

##########  دریافت پلن های خرید ########################################################
POST {{address}}/Profile/Bills/get_plans HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputShiftWorkId": "9",
    "inputTotalRequestKW": "2000"
}
########## ثبت خرید برق عادی ###############################################
POST   {{address}}/Profile/Bills/choose_plan HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPlanOrder": "3",  
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputShiftWorkId": "2",
    "inputTotalRequestKW": "1650"
}
########## ثبت خرید برق سبز ###############################################
POST   {{address}}/Profile/Bills/choose_plan_green HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPlanOrder": "4", 
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputShiftWorkId": "1",
    "inputTotalRequestKW": "500"
}

########## ثبت سفارش جهت پرداخت ###############################################
POST   {{address}}/Profile/Bills/start_payment HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputOrderId": "9"
}

