########## دریافت فهرست قبض های کاربر #################################################################################             
GET   {{address}}/Profile/Bills?page=1&inputBillTitle=&inputBillNumberId=&inputPersonLastName&inputPersonLastName=&inputPersonNationalCode=&inputPersonPhone= HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json 

########## دریافت تمامی قبض های کاربر #################################################################################             
GET   {{address}}/Profile/Bills/get_all HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

########## افزودن قبض #################################################################################             
POST   {{address}}/Profile/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillTitle": "قبض خانه شماره 1",
    "inputBillNumberId": "2254210233"
}
########## ویرایش قبض #################################################################################             
PUT   {{address}}/Profile/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "3302d7e2-0717-405b-9367-60fadf46a573",
    "inputBillTitle": "قبض خانه شماره 21",
    "inputBillNumberId": "2254210234"
}
########## حذف قبض #################################################################################             
DELETE   {{address}}/Profile/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillGUID": "3302d7e2-0717-405b-9367-60fadf46a573"
}

########## درج اطلاعات حقوقی و حقیقی قبض #################################################################################             
POST   {{address}}/Profile/Bills/add_legal_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPersonId": "1821",
    "inputBillGUID": "3302d7e2-0717-405b-9367-60fadf46a573",
    "inputRealName": "پدرام",
    "inputRealLastName": "محمدی",
    "inputRealNationalCode": "2541224518",
    "inputRealPhone": "09125745214",
    "inputRealProvinceId": "8",
    "inputRealCityId": "450",
    "inputRealAddress": "تهران شهریار خیابان ولیعصر عج الله تعالی فرجه الشریف",
    "inputLegalOrganizationName": "سازمان آب و فاضله ی آب",
    "inputLegalFinanceCode": "5541245",
    "inputLegalCompanyId": "12355001",
    "inputLegalRegisterNumber": "2258",
    "inputLegalPhone": "02155442211",
    "inputLegalProvinceId": "1",
    "inputLegalCityId": "459", 
    "inputLegalAddress": "تهران شهریار خیابان ", 
    "CreateDateTime": "1699089990",
    "CreatePersonId": "1821"
}
##########  دریافت جزئیات قبض کاربر #################################################################################
GET   {{address}}/Profile/Bills/power_data/e4c2ed78-0fd9-4fe9-9fcf-9225661167d2 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json 
##########  دریافت سابقه مصرف قبض کاربر #################################################################################
GET   {{address}}/Profile/Bills/sale_data/e4c2ed78-0fd9-4fe9-9fcf-9225661167d2 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json 