 ########## ویرایش اطلاعات کاربر #################################################################################
POST   {{address}}/Profile/Setting/change_user_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputFirstName": "محمد",
    "inputLastName": "تاجیک",
    "inputNationalCode": "2500354216",
    "inputAddress": "تهران خیابان ولیعصر روبروی ملت",
    "inputPersonProvinceId": "1",
    "inputPersonCityId": "444"
}

########## درج/ویرایش اطلاعات حقوقی کاربر ###########################################################################
POST   {{address}}/Profile/Setting/change_user_legal_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputLegalOrganizationName": "سازمان شماره 1 ",       
    "inputLegalFinanceCode": "1258003",             
    "inputLegalCompanyId": "215002100",            
    "inputLegalRegisterNumber": "13548",           
    "inputLegalPhone": "02165225522",                 
    "inputLegalProvinceId": "1",            
    "inputLegalCityId": "459",                  
    "inputLegalAddress": "تهران خیابان نیایش جنب پاساژ مرکزی" 
}
########## تغییر تلفن همراه #####################################################################################
POST   {{address}}/Profile/Setting/submit_new_phone HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPhone": "091205721070"
}

########## تایید تغییر تلفن همراه ###############################################################################
POST   {{address}}/Profile/Setting/verify_new_phone HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPhone": "09120570000",
    "inputVerifyCode": "2196"
}

########## دریافت اطلاعات فرد ####################################################################################
GET   {{address}}/Profile/Setting/get_user_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}

########## ارسال فایل ####################################################################################
POST {{address}}/Upload/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.pdf"
Content-Type: application/pdf

< ./file.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--