 ########## ویرایش اطلاعات کاربر #################################################################################
POST   {{address}}/Profile/Setting/change_user_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputFirstName": "بهنام",
    "inputLastName": "محمدی",
    "inputNationalCode": "2500354216",
    "inputAddress": "تهران خیابان ولیعصر روبروی پارک ملت"
}

########## ویرایش اطلاعات حقوقی کاربر ###########################################################################
POST   {{address}}/Profile/Setting/change_user_legal_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputLegalOrganizationName": "سازمان شماره 1 ",       
    "inputLegalFinanceCode": "1258003",             
    "inputLegalCompanyId": "215002100",            
    "inputLegalRegisterNumber": "13548",           
    "inputLegalPhone": "02165225522",                 
    "inputLegalProvinceId": "1",            
    "inputLegalCityId": "459",                  
    "inputLegalAddress": "تهران خیابان نیایش جنب پاساژ مرکزی" 
}
########## تغییر تلفن همراه #####################################################################################
POST   {{address}}/Profile/Setting/submit_new_phone HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPhone": "091205721070"
}

########## تایید تغییر تلفن همراه ###############################################################################
POST   {{address}}/Profile/Setting/verify_new_phone HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPhone": "09120570000",
    "inputVerifyCode": "2196"
}

########## دریافت اطلاعات فرد ####################################################################################
GET   {{address}}/Profile/Setting/get_user_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
}
