########## شبفت های کاری #################################################################################             
GET   {{address}}/Profile/ShiftWork?page=1&inputShiftWorkTitle=&inputShiftWorkBillGUID=&inputShiftWorkTitle= HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

########## افزودن شیفت کاری جهت خرید قبض ###############################################################       
POST   {{address}}/Profile/ShiftWork HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputShiftWorkTitle": "شیفت کاری شماره 1",
    "inputShiftWorkBillGUID": "45034857-e358-4213-b285-8ed79fb96757",
    "inputShiftWorkFromDate": "1402/08/01",
    "inputShiftWorkToDate": "1402/09/01", 
    "inputShiftWorkDays": 
    [
            {
                "DayTitle" : "شنبه",
                "DayValue" : "1",
                "Hour" :[
                            {  "FromHour" : "8",  "ToHour" : "10" },
                            {  "FromHour" : "12",  "ToHour" : "14" },
                            {  "FromHour" : "16",  "ToHour" : "20" }
                        ]
            },
            {
                "DayTitle" : "دوشنبه",
                "DayValue" : "3",
                "Hour" :[
                            {  "FromHour" : "8",  "ToHour" : "10" },
                            {  "FromHour" : "12",  "ToHour" : "14" },
                            {  "FromHour" : "16",  "ToHour" : "20" }
                        ]
            },
            {
                "DayTitle" : "چهارشنبه",
                "DayValue" : "5",
                "Hour" :[
                            {  "FromHour" : "8",  "ToHour" : "10" },
                            {  "FromHour" : "12",  "ToHour" : "14" },
                            {  "FromHour" : "16",  "ToHour" : "20" }
                        ]
            }
    ]
}
########## حذف شیفت کاری #################################################################################             
DELETE   {{address}}/Profile/ShiftWork HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputShiftWorkBillGUID": "3302d7e2-0717-405b-9367-60fadf46a573",
    "inputShiftWorkId": "9"
}
########## دریافت یک شیفت کاری #################################################################################             
GET   {{address}}/Profile/ShiftWork/get_shift_work/11/45034857-e358-4213-b285-8ed79fb96757 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json