  ########## دریافت فهرست قبض های کاربر #################################################################################             
GET   {{address}}/Admin/Bills?page=1&inputBillTitle=&inputBillNumberId=&inputPersonLastName&inputPersonLastName=&inputPersonNationalCode=&inputPersonPhone=&inputShowDeleted= HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

########## افزودن قبض برای کاربر #################################################################################             
POST   {{address}}/Admin/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputBillTitle": "قبض دستی",
    "inputPersonId" : "1820",
    "inputBillNumberId": "22542210234"
}
########## ویرایش قبض برای کاربر #################################################################################             
PUT   {{address}}/Admin/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPersonId" : "1820",
    "inputBillGUID": "98461e6f-cf9d-49a5-bc7e-2fc097dd507b",
    "inputBillTitle": "قبض خانه شماره 21",
    "inputBillNumberId": "2254210234"
}
##########  حذف قبض برای کاربر #################################################################################             
DELETE   {{address}}/Admin/Bills HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPersonId" : "1820",
    "inputBillGUID": "3302d7e2-0717-405b-9367-60fadf46a573"
}

########## درج اطلاعات حقوقی و حقیقی قبض برای کاربر #################################################################################             
POST   {{address}}/Profile/Bills/add_legal_info HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputPersonId": "1821",
    "inputBillGUID": "3302d7e2-0717-405b-9367-60fadf46a573",
    "inputRealName": "پدرام",
    "inputRealLastName": "محمدی",
    "inputRealNationalCode": "2541224518",
    "inputRealPhone": "09125745214",
    "inputRealProvinceId": "8",
    "inputRealCityId": "450",
    "inputRealAddress": "تهران شهریار خیابان ولیعصر عج الله تعالی فرجه الشریف",
    "inputLegalOrganizationName": "سازمان آب و فاضله ی آب",
    "inputLegalFinanceCode": "5541245",
    "inputLegalCompanyId": "12355001",
    "inputLegalRegisterNumber": "2258",
    "inputLegalPhone": "02155442211",
    "inputLegalProvinceId": "1",
    "inputLegalCityId": "459", 
    "inputLegalAddress": "تهران شهریار خیابان ", 
    "CreateDateTime": "1699089990",
    "CreatePersonId": "1821"
}
