  ########## دریافت فهرست تمامی قبض   #################################################################################             
GET   {{address}}/Admin/Orders?page=1&inputPersonFirstName=&inputPersonLastName&inputPersonNationalCode=&inputPersonPhone&inputOrderStatus=&inputBillTitle=&inputBillNumberId&inputStatus= HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

########## دریافت جزئیات کاربر  #################################################################################             
GET   {{address}}/Admin/Orders/get_order_detail/6 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
 
 
##########  تغییر وضعیت یک سفارش #################################################################################             
PUT   {{address}}/Admin/Orders HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputOrderId": "6",
    "inputBillGUID": "b9a6f23a-524a-452e-af50-85cc6b940270",
    "inputPersonId": "1823",
    "inputStatus": "Assigned"
}