##########  دریافت فهرست تعرفه استان ها #################################################################################             
GET   {{address}}/Admin/ProvinceTariff?page=1&inputProvinceName=&inputProvinceId= HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

##########  درج تعرفه یک استان #################################################################################             
POST   {{address}}/Admin/ProvinceTariff HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "inputProvinceId": "1",
    "inputLowPowerFromHour": "7",
    "inputLowPowerToHour": "10",
    "inputMiddlePowerFromHour": "14",
    "inputMiddlePowerToHour": "17",
    "inputPeakPowerFromHour": "20",
    "inputPeakPowerToHour": "22"
}
########## ویرایش تعرفه یک استان #################################################################################             
PUT   {{address}}/Admin/ProvinceTariff HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputProvinceTariffId": "1",
    "inputLowPowerFromHour": "7",
    "inputLowPowerToHour": "100",
    "inputMiddlePowerFromHour": "140",
    "inputMiddlePowerToHour": "170",
    "inputPeakPowerFromHour": "200",
    "inputPeakPowerToHour": "220"
}
########## حذف تعرفه استان #################################################################################             
DELETE   {{address}}/Admin/ProvinceTariff HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "inputProvinceTariffId" : "11"
}

########## ثبت قیمت برق #################################################################################             
POST   {{address}}/Admin/ProvinceTariff/add_electricity_price HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "inputHighPrice" : "960",
    "inputLowPrice" : "880"
}

########## ثبت قیمت برق سبز #################################################################################             
POST   {{address}}/Admin/ProvinceTariff/do_update_electricity_green_price HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
    "inputMonth" : "10",
    "inputGreenHighPrice" : "980",
    "inputGreenLowPrice" : "890",
    "inputGreenInventory" : "1800"
}
########## دریافت قیمت برق #################################################################################             
GET   {{address}}/Admin/ProvinceTariff/get_electricity_price HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
}

########## دریافت قیمت برق سبز #################################################################################             
GET   {{address}}/Admin/ProvinceTariff/get_electricity_green_price HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{ 
}

  