@address = http://localhost:8080/BargheToApi
//@address = https://api.bargheto.ir/auth
@version = v1
##################################### تست توکن ########################################
GET  {{address}}/Home/generate HTTP/1.1
Content-Type: application/json

{

}
################################# رمزگشایی ##########################
GET {{address}}/Home/is_ok
Authorization1: Bearer eyJhbGcXVCJ9 I6dHJ1ZSwicm9sZXMiOlsiQURNSU4iLCJBR0VOQ1kiXSwiZXhwaXJlX3RpbWUiOjE2OTg0OTI2MDN9.o79lw4q2vM9Sqejhthzxls6TrbsA_9QGgl7ERVaByaU
Content-Type: application/json

{

}
################################# دریافت اطلاعات توکن ##########################
GET {{address}}/Home/get_info
Authorization: Bearer eyJhbR5cCI6IkpXV cy1hZG1pbiI6dHJ1ZSwicm9sZXMiOlsiQURNSU4iLCJBR0VOQ1kiXSwiZXhwaXJlX3RpbWUiOjE2OTg0OTI2MDN9.o79lw4q2vM9Sqejhthzxls6TrbsA_9QGgl7ERVaByaU
Content-Type: application/json

{

}