########## دریافت کد امنیتی #################################################################################
GET   {{address}}/GetCaptcha HTTP/1.1
Content-Type: application/json

{
    
}
########## ثبت نام / لاگین #################################################################################
POST   {{address}}/Account/submit_phone HTTP/1.1
Content-Type: application/json

{
    "inputPhone": "09120572107",
    "inputCaptchaId": "c76ea039-6e76-4416-a97d-101fdf136c0b",
    "inputCaptchaCode" : "76800"
}
########## تایید کد ارسال شده ########################################################################
POST {{address}}/Account/verify_phone
Content-Type: application/json

{
    "inputPersonId": "1823",
    "inputVerifyCode" : "5916" 
}
