########## دریافت کد امنیتی #################################################################################
GET   {{address}}/GetCaptcha HTTP/1.1
Content-Type: application/json

{
    
}
########## ثبت نام / لاگین #################################################################################
POST   {{address}}/Account/submit_phone HTTP/1.1
Content-Type: application/json

{
    "inputPhone": "09120572107",
    "inputCaptchaId": "93c15faf-f448-4170-a649-1c31687fb769",
    "inputCaptchaCode" : "51132"
}
########## تایید کد ارسال شده ########################################################################
POST {{address}}/Account/verify_phone
Content-Type: application/json

{
    "inputPersonId": "1820",
    "inputVerifyCode" : "5692" 
}
